# Generated by Django 5.2.8 on 2025-11-20 08:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0002_alter_table_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp de creación.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp de última actualización.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único del plan nutricional.', primary_key=True, serialize=False)),
                ('auth_user_id', models.UUIDField(db_index=True, help_text='ID del usuario en Supabase (auth.users.id) al que pertenece este plan.')),
                ('title', models.CharField(help_text='Título del plan nutricional.', max_length=255)),
                ('language', models.CharField(default='es', help_text='Idioma del plan (ISO 639-1).', max_length=10)),
                ('issued_at', models.DateField(blank=True, help_text='Fecha de emisión del plan.', null=True)),
                ('valid_until', models.DateField(blank=True, db_index=True, help_text='Fecha de expiración del plan.', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el plan está activo o archivado.')),
                ('plan_data', models.JSONField(help_text='Estructura completa del plan nutricional siguiendo el esquema JSON. Incluye: plan (metadatos, source), subject (demographics), assessment (timeseries, diagnoses, goals), directives (meals, restrictions, substitutions), supplements, recommendations, activity_guidance y free_text.')),
                ('source_kind', models.CharField(blank=True, help_text='Tipo de fuente: pdf, image, text, web.', max_length=32, null=True)),
                ('source_uri', models.TextField(blank=True, help_text='URI o path del documento fuente.', null=True)),
                ('extracted_at', models.DateTimeField(blank=True, help_text='Fecha y hora de extracción del plan desde la fuente.', null=True)),
                ('extractor', models.CharField(blank=True, help_text='Nombre del sistema o método que extrajo el plan.', max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Plan Nutricional',
                'verbose_name_plural': 'Planes Nutricionales',
                'db_table': 'nutrition_plans',
                'ordering': ['-issued_at', '-created_at'],
                'indexes': [models.Index(fields=['auth_user_id', 'is_active'], name='nutrition_p_auth_us_1f5f06_idx'), models.Index(fields=['auth_user_id', 'valid_until'], name='nutrition_p_auth_us_29cb72_idx')],
            },
        ),
    ]
