# Generated by Django 5.2.8 on 2025-11-20 10:09

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0003_nutritionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionplan',
            name='created_by',
            field=models.UUIDField(blank=True, help_text='ID del profesional (Nutricionista) que creó o asignó este plan.', null=True),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='description',
            field=models.TextField(blank=True, help_text="Descripción interna para el profesional (ej. 'Keto para principiantes').", null=True),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='is_template',
            field=models.BooleanField(db_index=True, default=False, help_text='Si es True, este plan es una plantilla reutilizable.'),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='auth_user_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='ID del usuario en Supabase (auth.users.id) al que pertenece este plan.', null=True),
        ),
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp de creación.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp de última actualización.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único de la medición.', primary_key=True, serialize=False)),
                ('auth_user_id', models.UUIDField(db_index=True, help_text='ID del usuario (Paciente) al que pertenecen las medidas.')),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Fecha y hora de la toma de medidas.')),
                ('weight_kg', models.DecimalField(decimal_places=2, help_text='Peso corporal en Kilogramos.', max_digits=5)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Estatura en Centímetros.', max_digits=5, null=True)),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=1, help_text='Porcentaje de grasa corporal.', max_digits=4, null=True)),
                ('muscle_mass_percentage', models.DecimalField(blank=True, decimal_places=1, help_text='Porcentaje de masa muscular.', max_digits=4, null=True)),
                ('visceral_fat_level', models.PositiveSmallIntegerField(blank=True, help_text='Nivel de grasa visceral.', null=True)),
                ('waist_circumference_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Circunferencia de cintura en cm.', max_digits=5, null=True)),
                ('hip_circumference_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Circunferencia de cadera en cm.', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, help_text='Observaciones clínicas sobre la medición.', null=True)),
                ('measured_by', models.UUIDField(blank=True, help_text='ID del profesional que realizó la medición (si aplica).', null=True)),
                ('photos', models.JSONField(blank=True, default=list, help_text='Lista de URLs de fotos de progreso asociadas.')),
            ],
            options={
                'verbose_name': 'Medición Corporal',
                'verbose_name_plural': 'Mediciones Corporales',
                'db_table': 'body_measurements',
                'ordering': ['-recorded_at', '-created_at'],
                'indexes': [models.Index(fields=['auth_user_id', 'recorded_at'], name='body_measur_auth_us_6d3c4d_idx')],
            },
        ),
    ]
