# Generated by Django 5.2.8 on 2025-11-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0004_nutritionplan_created_by_nutritionplan_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodymeasurement',
            name='abdominal_skinfold_mm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Pliegue Abdominal (mm).', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='arm_flexed_circumference_cm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Brazo flexionado y contraído (cm).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='arm_relaxed_circumference_cm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Brazo relajado (cm).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='biceps_skinfold_mm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Pliegue Bicipital (mm).', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='IMC calculado automáticamente.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='calf_circumference_cm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Pantorrilla máxima (cm).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='calf_skinfold_mm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Pliegue Pantorrilla medial (mm).', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='ectomorphy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='endomorphy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='fat_mass_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Masa Grasa (kg).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='femur_breadth_mm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Diámetro bicondilar del fémur (mm).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='humerus_breadth_mm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Diámetro biepicondilar del húmero (mm).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='mesomorphy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='muscle_mass_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Masa Muscular (kg).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='patient_type',
            field=models.CharField(choices=[('sedentary', 'Sedentario'), ('active', 'Activo'), ('athlete', 'Deportista'), ('elderly', 'Adulto Mayor'), ('child', 'Niño/Adolescente')], default='sedentary', help_text='Clasificación del paciente al momento de la medición.', max_length=32),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='protocol',
            field=models.CharField(choices=[('isak_restricted', 'ISAK Perfil Restringido'), ('isak_full', 'ISAK Perfil Completo'), ('clinical_basic', 'Clínico Básico'), ('elderly_sarcopenia', 'Evaluación Adulto Mayor (Sarcopenia)'), ('self_reported', 'Auto-reportado')], default='clinical_basic', help_text='Protocolo utilizado para la toma de datos.', max_length=32),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='subscapular_skinfold_mm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Pliegue Subescapular (mm).', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='suprailiac_skinfold_mm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Pliegue Suprailiaco/Cresta Ilíaca (mm).', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='thigh_circumference_cm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Muslo medio (cm).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='thigh_skinfold_mm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Pliegue Muslo anterior (mm).', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='triceps_skinfold_mm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Pliegue Tricipital (mm).', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='waist_height_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='ICE', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='waist_hip_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='ICC', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='wrist_breadth_mm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Diámetro biestiloideo de muñeca (mm).', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='body_fat_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='% Grasa Corporal.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Estatura (cm).', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='hip_circumference_cm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Cadera máxima (cm).', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='measured_by',
            field=models.UUIDField(blank=True, help_text='ID del profesional.', null=True),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='muscle_mass_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='% Masa Muscular.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='notes',
            field=models.TextField(blank=True, help_text='Observaciones clínicas.', null=True),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='photos',
            field=models.JSONField(blank=True, default=list, help_text='URLs de fotos.'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='visceral_fat_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Nivel grasa visceral (BIA).', null=True),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='waist_circumference_cm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Cintura mínima (cm).', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, help_text='Peso corporal (kg).', max_digits=5),
        ),
        migrations.AddIndex(
            model_name='bodymeasurement',
            index=models.Index(fields=['protocol'], name='body_measur_protoco_c70569_idx'),
        ),
    ]
