# Generated by Django 5.2.7 on 2025-10-16 14:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='AppUser',
                    fields=[
                        ('id', models.BigAutoField(help_text='Clave sustituta para joins internos', primary_key=True, serialize=False)),
                        ('auth_user_id', models.UUIDField(db_index=True, help_text='Foreign key a auth.users.id para vinculación con autenticación', unique=True)),
                        ('full_name', models.TextField(help_text='Nombre completo legal mostrado en la aplicación')),
                        ('age', models.IntegerField(default=0, help_text='Edad en años; debe ser >= 0', validators=[django.core.validators.MinValueValidator(0)])),
                        ('email', models.TextField(db_index=True, help_text='Email principal de contacto. Debe ser único (case-insensitive)', unique=True)),
                        ('phone_number', models.TextField(blank=True, help_text='Teléfono de contacto opcional (formato E.164 preferido)', null=True)),
                        ('gender', models.TextField(blank=True, help_text='Descriptor de género auto-identificado (texto libre)', null=True)),
                        ('tier', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', help_text='Plan de membresía del usuario', max_length=20)),
                        ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp de creación del registro')),
                        ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp de última actualización (auto-actualizado por trigger)')),
                    ],
                    options={
                        'verbose_name': 'Usuario de Aplicación',
                        'verbose_name_plural': 'Usuarios de Aplicación',
                        'db_table': 'app_users',
                        'ordering': ['-created_at'],
                        'managed': False,
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Identificador estable del plan (ej. free, core, plus, premium).', max_length=32, unique=True)),
                ('name', models.CharField(help_text='Nombre legible del plan mostrado en la interfaz.', max_length=64)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio mensual de referencia en USD para cálculos de facturación.', max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('report_frequency', models.CharField(choices=[('monthly', 'Mensual'), ('weekly', 'Semanal'), ('on_demand', 'Bajo demanda')], default='monthly', help_text='Frecuencia de generación automática de reportes metabólicos.', max_length=16)),
                ('reports_per_period', models.PositiveIntegerField(blank=True, help_text='Número máximo de reportes por periodo. Null indica ilimitado.', null=True)),
                ('realtime_interval_minutes', models.PositiveIntegerField(blank=True, help_text='Intervalo mínimo en minutos para actualizaciones en tiempo real. Null deshabilita la funcionalidad.', null=True)),
                ('chatbot_messages_per_day', models.PositiveIntegerField(blank=True, help_text='Mensajes del chatbot permitidos por día. Null indica sin acceso.', null=True)),
                ('scientific_library_access', models.BooleanField(default=False, help_text='Permite acceder a referencias de la biblioteca científica.')),
                ('preventive_recommendations', models.BooleanField(default=False, help_text='Habilita recomendaciones proactivas basadas en IA.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Configuraciones adicionales específicas del plan.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan de Suscripción',
                'verbose_name_plural': 'Planes de Suscripción',
                'ordering': ['monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='UsageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_code', models.CharField(help_text='Recurso controlado (ej. metabolic_report, chatbot_session).', max_length=64)),
                ('limit', models.PositiveIntegerField(blank=True, help_text='Cantidad máxima por periodo. Null representa ilimitado.', null=True)),
                ('period', models.CharField(choices=[('daily', 'Diaria'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('unlimited', 'Ilimitada')], default='monthly', help_text='Periodo en el que se reinicia la cuota.', max_length=16)),
                ('notes', models.TextField(blank=True, help_text='Descripción del alcance de la cuota o excepciones.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Campos adicionales (p. ej. intervalo horario, ventana rolling).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.ForeignKey(help_text='Plan al que pertenece la cuota.', on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='users.subscriptiontier')),
            ],
            options={
                'verbose_name': 'Cuota de Consumo',
                'verbose_name_plural': 'Cuotas de Consumo',
                'unique_together': {('tier', 'resource_code')},
            },
        ),
        migrations.CreateModel(
            name='UsageLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_code', models.CharField(help_text='Recurso consumido (ej. chatbot_session).', max_length=64)),
                ('amount', models.PositiveIntegerField(default=1, help_text='Cantidad consumida en el evento.')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp en que se registró el consumo.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales (p. ej. origen, identificador de reporte).')),
                ('user', models.ForeignKey(db_constraint=False, help_text='Usuario asociado al consumo registrado.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='usage_events', to='users.appuser')),
                ('quota', models.ForeignKey(blank=True, help_text='Cuota aplicada en el momento del consumo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to='users.usagequota')),
            ],
            options={
                'verbose_name': 'Movimiento de Consumo',
                'verbose_name_plural': 'Movimientos de Consumo',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['resource_code', 'occurred_at'], name='idx_usage_resource'), models.Index(fields=['user', 'occurred_at'], name='idx_usage_user_time')],
            },
        ),
    ]
