# Generated by Django 5.2.7 on 2025-10-16

from django.db import migrations


def seed_subscription_data(apps, schema_editor):
    SubscriptionTier = apps.get_model('users', 'SubscriptionTier')
    UsageQuota = apps.get_model('users', 'UsageQuota')

    tiers = {
        'free': {
            'name': 'Free',
            'monthly_price': 0,
            'report_frequency': 'monthly',
            'reports_per_period': 1,
            'realtime_interval_minutes': 10080,  # una vez por semana
            'chatbot_messages_per_day': None,
            'scientific_library_access': False,
            'preventive_recommendations': False,
        },
        'core': {
            'name': 'Core',
            'monthly_price': 5,
            'report_frequency': 'weekly',
            'reports_per_period': 2,
            'realtime_interval_minutes': 360,  # cada 6 horas
            'chatbot_messages_per_day': None,
            'scientific_library_access': False,
            'preventive_recommendations': False,
        },
        'plus': {
            'name': 'Plus',
            'monthly_price': 15,
            'report_frequency': 'weekly',
            'reports_per_period': 1,
            'realtime_interval_minutes': 120,
            'chatbot_messages_per_day': 20,
            'scientific_library_access': False,
            'preventive_recommendations': True,
        },
        'premium': {
            'name': 'Premium',
            'monthly_price': 30,
            'report_frequency': 'on_demand',
            'reports_per_period': None,
            'realtime_interval_minutes': 1,
            'chatbot_messages_per_day': 100,
            'scientific_library_access': True,
            'preventive_recommendations': True,
            'metadata': {
                'scientific_library': 'full_access',
                'chatbot_priority': 'realtime',
            },
        },
    }

    created_tiers = {}
    for code, attrs in tiers.items():
        metadata = attrs.pop('metadata', {})
        tier, _ = SubscriptionTier.objects.update_or_create(
            code=code,
            defaults={**attrs, 'metadata': metadata},
        )
        created_tiers[code] = tier

    quotas = [
        # Free
        {'tier': 'free', 'resource_code': 'metabolic_report', 'limit': 1, 'period': 'monthly'},
        {'tier': 'free', 'resource_code': 'realtime_update', 'limit': 1, 'period': 'weekly', 'notes': 'Actualización semanal en vistas.'},
        # Core
        {'tier': 'core', 'resource_code': 'metabolic_report', 'limit': 2, 'period': 'weekly'},
        {'tier': 'core', 'resource_code': 'realtime_update', 'limit': None, 'period': 'unlimited', 'metadata': {'interval_minutes': 360}},
        # Plus
        {'tier': 'plus', 'resource_code': 'metabolic_report', 'limit': 1, 'period': 'weekly'},
        {'tier': 'plus', 'resource_code': 'realtime_update', 'limit': None, 'period': 'unlimited', 'metadata': {'interval_minutes': 120}},
        {'tier': 'plus', 'resource_code': 'chatbot_session', 'limit': 20, 'period': 'daily'},
        # Premium
        {'tier': 'premium', 'resource_code': 'metabolic_report', 'limit': None, 'period': 'unlimited'},
        {'tier': 'premium', 'resource_code': 'realtime_update', 'limit': None, 'period': 'unlimited', 'metadata': {'interval_minutes': 1}},
        {'tier': 'premium', 'resource_code': 'chatbot_session', 'limit': 100, 'period': 'daily', 'metadata': {'priority': 'realtime'}},
        {'tier': 'premium', 'resource_code': 'vector_search', 'limit': None, 'period': 'unlimited'},
        {'tier': 'premium', 'resource_code': 'preventive_alert', 'limit': None, 'period': 'daily'},
    ]

    for quota in quotas:
        metadata = quota.pop('metadata', {})
        tier_code = quota.pop('tier')
        tier = created_tiers[tier_code]
        UsageQuota.objects.update_or_create(
            tier=tier,
            resource_code=quota['resource_code'],
            defaults={**quota, 'metadata': metadata},
        )


def unseed_subscription_data(apps, schema_editor):
    SubscriptionTier = apps.get_model('users', 'SubscriptionTier')
    UsageQuota = apps.get_model('users', 'UsageQuota')

    UsageQuota.objects.filter(
        resource_code__in=[
            'metabolic_report',
            'realtime_update',
            'chatbot_session',
            'vector_search',
            'preventive_alert',
        ]
    ).delete()
    SubscriptionTier.objects.filter(code__in=['free', 'core', 'plus', 'premium']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_subscription_data, unseed_subscription_data),
    ]
