# Generated by Django AURA360 on 2025-10-27

from __future__ import annotations

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Migración inicial para la app holistic."""

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HolisticRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp de creación.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp de última actualización.",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        db_index=True,
                        help_text="Identificador del usuario en el sistema externo.",
                        max_length=64,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("mind", "Mente"),
                            ("body", "Cuerpo"),
                            ("soul", "Alma"),
                        ],
                        help_text="Categoría solicitada por el cliente.",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("completed", "Completada"),
                            ("failed", "Fallida"),
                        ],
                        default="pending",
                        help_text="Estado actual de la solicitud.",
                        max_length=16,
                    ),
                ),
                (
                    "trace_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador de trazabilidad correlacionado con agentes y logs.",
                        unique=True,
                    ),
                ),
                (
                    "request_payload",
                    models.JSONField(
                        default=dict,
                        help_text="Payload original recibido desde el cliente.",
                    ),
                ),
                (
                    "response_payload",
                    models.JSONField(
                        blank=True,
                        help_text="Respuesta final enviada al cliente.",
                        null=True,
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        blank=True,
                        help_text="Categoría de error si la solicitud falla.",
                        max_length=128,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=("category",),
                        name="holistic_request_category_idx",
                    ),
                    models.Index(
                        fields=("trace_id",),
                        name="holistic_request_trace_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HolisticAgentRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp de creación.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp de última actualización.",
                    ),
                ),
                (
                    "agent_name",
                    models.CharField(
                        help_text="Nombre o identificador del agente invocado.",
                        max_length=128,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("running", "En ejecución"),
                            ("completed", "Completada"),
                            ("failed", "Fallida"),
                        ],
                        default="pending",
                        help_text="Estado actual de la ejecución del agente.",
                        max_length=16,
                    ),
                ),
                (
                    "latency_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Latencia total de la ejecución del agente en milisegundos.",
                        null=True,
                    ),
                ),
                (
                    "input_context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Contexto estructurado enviado al agente.",
                    ),
                ),
                (
                    "output_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Respuesta cruda retornada por el agente.",
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        blank=True,
                        help_text="Categoría de error si la ejecución falló.",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        help_text="Solicitud asociada a la ejecución del agente.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_runs",
                        to="holistic.holisticrequest",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=("agent_name",),
                        name="holistic_agent_run_agent_idx",
                    ),
                    models.Index(
                        fields=("status",),
                        name="holistic_agent_run_status_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HolisticAgentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp de creación.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp de última actualización.",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("mind", "Mente"),
                            ("body", "Cuerpo"),
                            ("soul", "Alma"),
                        ],
                        help_text="Categoría a la que aplica el perfil de agente.",
                        max_length=16,
                    ),
                ),
                (
                    "primary_agent",
                    models.CharField(
                        help_text="Identificador del agente principal a invocar.",
                        max_length=128,
                    ),
                ),
                (
                    "fallback_agents",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de agentes alternos en orden de prioridad.",
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        help_text="Modelo de embeddings recomendado para la categoría.",
                        max_length=128,
                    ),
                ),
                (
                    "prompt_template",
                    models.TextField(
                        help_text="Plantilla de prompt base utilizada por el agente.",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0.0",
                        help_text="Versión de la configuración del perfil.",
                        max_length=32,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el perfil está activo para su categoría.",
                    ),
                ),
            ],
            options={
                "ordering": ("category", "-version"),
                "indexes": [
                    models.Index(
                        fields=("category", "is_active"),
                        name="holistic_profile_active_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HolisticVectorQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp de creación.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp de última actualización.",
                    ),
                ),
                (
                    "vector_store",
                    models.CharField(
                        help_text="Nombre del almacén vectorial utilizado.",
                        max_length=128,
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        help_text="Modelo de embeddings utilizado para la consulta.",
                        max_length=128,
                    ),
                ),
                (
                    "query_text",
                    models.TextField(
                        help_text="Texto de la consulta realizada.",
                    ),
                ),
                (
                    "top_k",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Número de resultados solicitados al servicio vectorial.",
                    ),
                ),
                (
                    "response_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Respuesta completa del servicio vectorial.",
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Confianza agregada de los resultados retornados.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "agent_run",
                    models.ForeignKey(
                        help_text="Ejecución de agente asociada a la consulta vectorial.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vector_queries",
                        to="holistic.holisticagentrun",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=("vector_store",),
                        name="holistic_vector_store_idx",
                    ),
                ],
            },
        ),
        migrations.AlterUniqueTogether(
            name="holisticagentprofile",
            unique_together={("category", "version")},
        ),
    ]