# Generated by Django 5.2.7 on 2025-11-05 19:08

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holistic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileExtended',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp de creación.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp de última actualización.')),
                ('auth_user_id', models.UUIDField(help_text='ID del usuario en Supabase auth.users (1-to-1 con AppUser)', primary_key=True, serialize=False)),
                ('ikigai_passion', models.JSONField(blank=True, default=list, help_text='Lo que amas hacer (lista de strings)')),
                ('ikigai_mission', models.JSONField(blank=True, default=list, help_text='Lo que el mundo necesita (lista de strings)')),
                ('ikigai_vocation', models.JSONField(blank=True, default=list, help_text='Por lo que te pueden pagar (lista de strings)')),
                ('ikigai_profession', models.JSONField(blank=True, default=list, help_text='En lo que eres bueno (lista de strings)')),
                ('ikigai_statement', models.TextField(blank=True, default='', help_text='Declaración personal de propósito de vida')),
                ('psychosocial_context', models.TextField(blank=True, default='', help_text='Contexto psicosocial del usuario')),
                ('support_network', models.TextField(blank=True, default='', help_text='Red de apoyo del usuario')),
                ('current_stressors', models.TextField(blank=True, default='', help_text='Estresores actuales del usuario')),
            ],
            options={
                'db_table': 'user_profiles_extended',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp de creación.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp de última actualización.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auth_user_id', models.UUIDField(db_index=True, help_text='ID del usuario en Supabase auth.users')),
                ('recorded_at', models.DateTimeField(db_index=True, help_text='Timestamp cuando el usuario registró este mood')),
                ('level', models.CharField(choices=[('very_low', 'Muy bajo'), ('low', 'Bajo'), ('moderate', 'Moderado'), ('good', 'Bueno'), ('excellent', 'Excelente')], help_text='Nivel de estado de ánimo', max_length=16)),
                ('note', models.TextField(blank=True, default='', help_text='Nota opcional del usuario sobre su estado')),
                ('tags', models.JSONField(blank=True, default=list, help_text="Tags categorizing the mood (e.g., ['work_stress', 'tired'])")),
            ],
            options={
                'db_table': 'mood_entries',
                'ordering': ('-recorded_at',),
                'indexes': [models.Index(fields=['auth_user_id', 'recorded_at'], name='mood_entry_user_time_idx'), models.Index(fields=['level'], name='mood_entry_level_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserContextSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp de creación.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp de última actualización.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auth_user_id', models.UUIDField(db_index=True, help_text='ID del usuario en Supabase auth.users')),
                ('snapshot_type', models.CharField(choices=[('mind', 'Mind'), ('body', 'Body'), ('soul', 'Soul'), ('holistic', 'Holistic')], help_text='Tipo de snapshot: mind, body, soul, o holistic', max_length=16)),
                ('timeframe', models.CharField(choices=[('7d', '7 días'), ('30d', '30 días'), ('90d', '90 días')], default='7d', help_text='Ventana temporal de los datos agregados', max_length=8)),
                ('consolidated_text', models.TextField(help_text='Texto consolidado listo para embedding')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadata adicional específica del snapshot (stats, etc.)')),
                ('topics', models.JSONField(blank=True, default=list, help_text='Topics biomédicos clasificados para este snapshot')),
                ('confidence_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Score de confianza del snapshot (0.00-1.00)', max_digits=5)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si este snapshot está activo (solo uno por tipo/timeframe)')),
                ('vectorized_at', models.DateTimeField(blank=True, help_text='Timestamp de cuando se vectorizó en Qdrant', null=True)),
                ('vector_doc_id', models.CharField(blank=True, help_text='ID del documento en Qdrant', max_length=255, null=True)),
                ('user_consent_given', models.BooleanField(default=False, help_text='Usuario dio consentimiento para almacenar embeddings')),
                ('consent_given_at', models.DateTimeField(blank=True, help_text='Timestamp del consentimiento', null=True)),
            ],
            options={
                'db_table': 'user_context_snapshots',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['auth_user_id', 'is_active'], name='user_context_user_active_idx'), models.Index(fields=['snapshot_type', 'timeframe'], name='user_context_type_time_idx'), models.Index(fields=['vectorized_at'], name='user_context_vectorized_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('auth_user_id', 'snapshot_type', 'timeframe'), name='unique_active_snapshot_per_user_type_time')],
            },
        ),
    ]
