# Generated by Django 5.2.8 on 2025-11-13 05:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holistic', '0002_userprofileextended_moodentry_usercontextsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeSubmission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp de creación.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp de última actualización.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auth_user_id', models.UUIDField(db_index=True, help_text='ID del usuario en Supabase auth.users')),
                ('trace_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador de trazabilidad para correlacionar etapas del pipeline.', unique=True)),
                ('answers', models.JSONField(blank=True, default=dict, help_text='Mapa question_id -> valor normalizado del cuestionario (12 reactivos).')),
                ('free_text', models.CharField(blank=True, default='', help_text='Campo libre final provisto por el participante (máx. 280 caracteres).', max_length=280)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'En proceso'), ('ready', 'Lista'), ('failed', 'Fallida')], default='pending', help_text='Estado actual del procesamiento del intake.', max_length=16)),
                ('processing_stage', models.CharField(blank=True, default='', help_text='Última etapa completada (ej. collected, contextualized, report_ready).', max_length=64)),
                ('vectorize_snapshot', models.BooleanField(default=True, help_text='Si es True, el snapshot holístico generado se vectoriza en Qdrant.')),
                ('estimated_wait_seconds', models.PositiveSmallIntegerField(default=60, help_text='Tiempo estimado de espera mostrado al usuario.')),
                ('report_url', models.URLField(blank=True, help_text='URL firmada del PDF personalizado, si ya está disponible.', max_length=512, null=True)),
                ('report_storage_path', models.CharField(blank=True, default='', help_text='Ruta interna en el storage donde vive el PDF final.', max_length=255)),
                ('report_metadata', models.JSONField(blank=True, default=dict, help_text='Metadata adicional del reporte (checksum, número de páginas, etc.).')),
                ('failure_reason', models.TextField(blank=True, default='', help_text='Descripción breve del fallo cuando status=failed.')),
                ('last_error_at', models.DateTimeField(blank=True, help_text='Timestamp del último error registrado para este intake.', null=True)),
            ],
            options={
                'db_table': 'intake_submissions',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['auth_user_id', 'status'], name='intake_user_status_idx'), models.Index(fields=['trace_id'], name='intake_trace_idx')],
            },
        ),
    ]
